name: push_messaging_flutter
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  bloc: 8.1.0
  bloc_concurrency: 0.2.0
  cupertino_icons: ^1.0.2
  flutter_bloc: 8.1.1
  firebase_core: ^2.1.1
  firebase_messaging: ^14.0.4
  json_serializable: 6.3.2
  flutter_local_notifications: 9.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: "2.3.0"
  built_value_generator: "8.4.1"
  flutter_lints: "2.0.1"
  freezed: "2.2.0"


flutter:
  uses-material-design: true

